services:
  mongo:
    image: mongo:7
    container_name: movie-atlas-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: movie-atlas-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: movie-atlas-app
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017/movie-api-db
      MONGO_DATABASE: movie-api-db
      APP_CATALOG_SEED_ON_STARTUP: "true"
      APP_CACHE_REDIS_ENABLED: "true"
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
    ports:
      - "8080:8080"

volumes:
  mongo-data:
