services:
  - type: web
    name: movie-atlas
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DATABASE
        value: movie-api-db
      - key: APP_CATALOG_SEED_ON_STARTUP
        value: "true"
      - key: APP_CACHE_REDIS_ENABLED
        value: "false"
      - key: APP_MESSAGING_RABBITMQ_ENABLED
        value: "false"
      - key: APP_COLLABORATIVE_ENABLED
        value: "true"
      - key: SPRING_AUTOCONFIGURE_EXCLUDE
        value: "org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration"
