spring.config.import=optional:file:.env[.properties]
spring.application.name=Movie
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/${MONGO_DATABASE:movie-api-db}}
spring.mongodb.database=${MONGO_DATABASE:movie-api-db}

app.catalog.seed-on-startup=${APP_CATALOG_SEED_ON_STARTUP:true}
